import type { Professional } from "@/types/professional";

export const professionals: Professional[] = [
  {
    id: "antero-montalvo",
    nombre: "Antero Montalvo",
    cargo: "Arquitecto de Software y Senior Full Stack Engineer",
    resumenProfesional:
      "Profesional de desarrollo de software con más de cuatro años de experiencia implementando soluciones para los sectores público, seguros, comercio electrónico, recursos humanos y tecnología. Cuenta con experiencia en microservicios, integración de sistemas, soluciones cloud y modernización de aplicaciones.",
    formacionAcademica: ["Desarrollo de Software – SENATI"],
    experienciaGeneral: "4+ años",
    experienciaEspecifica: [
      "Desarrollo de soluciones con Node.js, NestJS, .NET, Java, Golang, Angular y React.",
      "Diseño y desarrollo de APIs REST y microservicios.",
      "Aplicación de Clean Architecture, arquitectura hexagonal, CQRS y principios SOLID.",
      "Implementación de soluciones sobre AWS.",
      "Integración con ERP, RENIEC, Equifax y plataformas de pago.",
      "Desarrollo de plataformas para entidades públicas y empresas privadas.",
      "Automatización mediante inteligencia artificial, RAG, n8n y Node-RED.",
      "Dockerización, despliegues y automatización CI/CD.",
    ],
    especialidades: [
      "Arquitectura de software",
      "Microservicios",
      "Cloud y DevOps",
      "Integraciones",
    ],
    tecnologias: [
      "Node.js",
      "NestJS",
      ".NET",
      "Java",
      "Spring Boot",
      "Golang",
      "Angular",
      "React",
      "AWS",
      "Docker",
      "PostgreSQL",
      "SQL Server",
      "Oracle",
      "MySQL",
      "MongoDB",
    ],
    capacitaciones: [
      "AWS Cloud Practitioner",
      "Scrum Foundation Professional",
      "Desarrollo backend escalable con NestJS",
      "NestJS y GraphQL",
    ],
    certificaciones: [
      "AWS Cloud Practitioner",
      "Scrum Foundation Professional",
    ],
    sectores: [
      "Gobierno",
      "Seguros",
      "E-commerce",
      "Recursos humanos",
      "Tecnología",
    ],
    proyectosDestacados: [
      "Plataformas para entidades públicas",
      "Sistemas de integración con ERP",
      "Soluciones de automatización con IA",
    ],
    perfilDestacado: true,
    orden: 1,
  },
  {
    id: "victor-santos",
    nombre: "Víctor Francisco Santos Santiago",
    cargo: "Programador Senior y Coordinador de Sistemas",
    resumenProfesional:
      "Ingeniero de Sistemas e Informática con amplia experiencia en desarrollo de software, coordinación tecnológica, infraestructura, bases de datos y continuidad operativa. Ha trabajado en empresas privadas y en la Superintendencia de Banca, Seguros y AFP.",
    formacionAcademica: [
      "Titulado en Ingeniería de Sistemas e Informática – Universidad Norbert Wiener",
      "Bachiller en Ingeniería de Sistemas y Cómputo – Universidad Inca Garcilaso de la Vega",
    ],
    experienciaGeneral: "10+ años",
    experienciaEspecifica: [
      "Desarrollo Full Stack con .NET, Spring Boot y Angular.",
      "Desarrollo y mantenimiento de APIs REST.",
      "Gestión de SQL Server, PostgreSQL, MySQL y Oracle.",
      "Administración de servidores e infraestructura corporativa.",
      "Coordinación de requerimientos tecnológicos.",
      "Facturación electrónica e integración con NubeFact.",
      "Desarrollo de aplicaciones empresariales.",
      "Despliegues sobre IIS y Docker.",
      "Experiencia en la Superintendencia de Banca, Seguros y AFP.",
    ],
    especialidades: [
      "Liderazgo técnico",
      "Backend",
      "Bases de datos",
      "Integraciones",
    ],
    tecnologias: [
      ".NET",
      "C#",
      "Spring Boot",
      "Angular",
      "JavaScript",
      "PHP",
      "Docker",
      "AWS",
      "Azure",
      "SQL Server",
      "PostgreSQL",
      "MySQL",
      "Oracle",
    ],
    capacitaciones: [
      "Architecture .NET 9",
      ".NET 9 Design: Principles & Patterns",
      "Full Stack con Spring Boot 3 y Angular 18",
      "ASP.NET Developer: Enterprise Applications",
      "Arquitectura de datos en AWS",
      "Full Stack .NET y Angular",
      "Desarrollo web con Visual Studio",
      "Java y servicios web RESTful",
    ],
    certificaciones: [],
    sectores: [
      "Financiero",
      "Telecomunicaciones",
      "Comercio",
      "Servicios",
      "Sector público",
    ],
    proyectosDestacados: [
      "Sistemas para la Superintendencia de Banca, Seguros y AFP",
      "Plataformas de facturación electrónica",
      "Aplicaciones empresariales corporativas",
    ],
    perfilDestacado: true,
    orden: 2,
  },
  {
    id: "yan-pool-valencia",
    nombre: "Yan Pool Valencia Orrego",
    cargo: "Senior Full Stack Developer",
    resumenProfesional:
      "Bachiller en Ingeniería de Sistemas con más de diez años de participación en desarrollo, mantenimiento e integración de aplicaciones empresariales. Cuenta con experiencia en proyectos para banca, seguros, contact centers, comercio electrónico y empresas proveedoras del Estado.",
    formacionAcademica: [
      "Bachiller en Ingeniería de Sistemas – Universidad Autónoma del Perú",
    ],
    experienciaGeneral: "10+ años",
    experienciaEspecifica: [
      "Desarrollo Full Stack con React, Angular, C#, Java, PHP y Node.js.",
      "Desarrollo de aplicaciones para procesamiento de información bancaria.",
      "Desarrollo y mantenimiento de plataformas empresariales.",
      "Administración de servidores Linux, Windows y AWS.",
      "Integración entre aplicaciones.",
      "Desarrollo de soluciones web para empresas privadas y entidades públicas.",
      "Optimización de rendimiento y tiempos de carga.",
      "Desarrollo de reportes y automatizaciones.",
    ],
    especialidades: ["Full Stack", "Backend", "Frontend", "Integraciones"],
    tecnologias: [
      "React",
      "Angular",
      "Node.js",
      "C#",
      ".NET",
      "Java",
      "PHP",
      "JavaScript",
      "MySQL",
      "SQL Server",
      "Oracle",
      "Linux",
      "AWS",
    ],
    capacitaciones: [
      "Gestión de proyectos",
      "Inglés básico",
      "Formación complementaria en administración de servidores y herramientas empresariales",
    ],
    certificaciones: [],
    sectores: [
      "Banca",
      "Seguros",
      "Comercio electrónico",
      "Telecomunicaciones",
      "Sector público",
    ],
    proyectosDestacados: [
      "Aplicaciones para procesamiento bancario",
      "Plataformas empresariales de comercio electrónico",
      "Soluciones web para entidades públicas",
    ],
    perfilDestacado: true,
    orden: 3,
  },
  {
    id: "anaiz-rojas",
    nombre: "Anaiz Gianella Rojas Senteno",
    cargo: "Especialista Backend e Integraciones SAP",
    resumenProfesional:
      "Bachiller en Ingeniería de Sistemas Computacionales con más de tres años de experiencia desarrollando soluciones empresariales con C# y .NET. Especializada en SAP Business One, APIs REST, SQL Server, SAP HANA y automatización de procesos.",
    formacionAcademica: [
      "Bachiller en Ingeniería de Sistemas Computacionales – Universidad Privada del Norte",
    ],
    experienciaGeneral: "3+ años",
    experienciaEspecifica: [
      "Desarrollo backend con C# y .NET.",
      "Integración de SAP Business One con ecommerce, CRM y proveedores.",
      "Implementación de APIs REST y servicios Windows.",
      "Desarrollo y optimización de procedimientos en SQL Server y SAP HANA.",
      "Automatización mediante Python, Django, Celery y Redis.",
      "Desarrollo de portales integrados con SAP.",
      "Despliegue sobre IIS, Nginx, Gunicorn y Linux.",
      "Coordinación técnica con clientes y usuarios funcionales.",
    ],
    especialidades: [
      "Backend",
      "Integraciones",
      "Bases de datos",
      "Arquitectura",
    ],
    tecnologias: [
      "C#",
      ".NET",
      "SAP Business One",
      "SAP HANA",
      "SQL Server",
      "Python",
      "Django",
      "React",
      "Vue",
      "PostgreSQL",
      "Redis",
      "IIS",
      "Linux",
    ],
    capacitaciones: [
      "Arquitectura de Software – TECSUP, 180 horas",
      "Desarrollo Web Full Stack con Python – TECSUP, 258 horas",
      "Java Developer – Universidad Nacional de Ingeniería",
      "Administración de bases de datos",
      "SQL Server 2016: implementación y administración",
    ],
    certificaciones: [
      "Diseñador de Software",
      "CCNA: redes, switching, routing e IoT",
      "PCAP: Programming Essentials in Python",
      "Advanced Programming in C++",
    ],
    sectores: [
      "ERP",
      "Comercio electrónico",
      "Facturación",
      "CRM",
      "Automatización empresarial",
    ],
    proyectosDestacados: [
      "Integraciones SAP Business One con ecommerce",
      "Portales empresariales integrados con SAP",
      "Automatización de procesos con Python",
    ],
    perfilDestacado: true,
    orden: 4,
  },
  {
    id: "angel-falcon",
    nombre: "Ángel Giovani Falcón Falconi",
    cargo: "Desarrollador Full Stack y Especialista QA",
    resumenProfesional:
      "Bachiller en Ingeniería de Software con experiencia en análisis, desarrollo, facturación, soporte de aplicaciones empresariales, calidad de software y gestión de despliegues.",
    formacionAcademica: [
      "Bachiller en Ingeniería de Software – Universidad Nacional Mayor de San Marcos",
    ],
    experienciaGeneral: "3+ años",
    experienciaEspecifica: [
      "Desarrollo Full Stack con C#, .NET, Angular, Next.js y JavaScript.",
      "Análisis y desarrollo de procesos de facturación.",
      "Automatización e integración de sistemas mediante Node-RED.",
      "Optimización de procedimientos almacenados y jobs en SQL Server.",
      "Pruebas funcionales, regresión y automatización con Selenium.",
      "Gestión de despliegues y pases a producción.",
      "Atención de incidencias críticas y análisis de causa raíz.",
      "Experiencia temporal liderando equipos y distribuyendo actividades.",
    ],
    especialidades: [
      "QA y automatización",
      "Full Stack",
      "Backend",
      "Integraciones",
    ],
    tecnologias: [
      "C#",
      ".NET",
      "Angular",
      "Next.js",
      "JavaScript",
      "Node-RED",
      "SQL Server",
      "MySQL",
      "Oracle",
      "PostgreSQL",
      "AWS S3",
      "AWS Athena",
      "Selenium",
      "GitLab",
    ],
    capacitaciones: [],
    certificaciones: [],
    sectores: [
      "Telecomunicaciones",
      "Facturación",
      "Educación",
      "Sistemas empresariales",
    ],
    proyectosDestacados: [
      "Sistemas de facturación empresarial",
      "Automatización de pruebas con Selenium",
      "Gestión de despliegues a producción",
    ],
    perfilDestacado: true,
    orden: 5,
  },
  {
    id: "carlos-herrera",
    nombre: "Carlos Daniel Herrera Calero",
    cargo: "Desarrollador Full Stack y Co-líder Técnico",
    resumenProfesional:
      "Profesional técnico en Diseño y Desarrollo de Software con experiencia desarrollando aplicaciones web, APIs, microservicios y soluciones móviles. Ha participado en la coordinación técnica de equipos y en la planificación de despliegues a producción.",
    formacionAcademica: [
      "Diseño y Desarrollo de Software – TECSUP",
    ],
    experienciaGeneral: "3+ años",
    experienciaEspecifica: [
      "Desarrollo frontend con React y Angular.",
      "Desarrollo backend con C#, .NET y Node.js.",
      "Implementación de microservicios y patrón BFF.",
      "Integración con Redis, Kafka y WebSockets.",
      "Gestión de SQL Server, PostgreSQL y MongoDB.",
      "Desarrollo móvil con React Native.",
      "Implementación de soluciones sobre AWS.",
      "Coordinación de equipos y seguimiento de colaboradores.",
      "Planificación y ejecución de pases a producción.",
      "Desarrollo de módulos asistidos por inteligencia artificial.",
    ],
    especialidades: [
      "Full Stack",
      "Cloud y DevOps",
      "Liderazgo técnico",
      "Integraciones",
    ],
    tecnologias: [
      "React",
      "Angular",
      "React Native",
      "C#",
      ".NET",
      "Node.js",
      "Redis",
      "Kafka",
      "WebSockets",
      "Docker",
      "AWS",
      "SQL Server",
      "PostgreSQL",
      "MongoDB",
    ],
    capacitaciones: [
      "Scrum Foundation",
      "Fundamentos de arquitectura de software",
      "Docker profesional",
      "Introducción a DevOps",
      "JavaScript Essentials",
      "Fundamentos de SQL",
      "Ingeniería de prompts",
      "Desarrollo con inteligencia artificial",
      "GitHub Copilot y Microsoft Copilot",
    ],
    certificaciones: ["Scrum Foundation"],
    sectores: [
      "Telecomunicaciones",
      "Seguros",
      "Recursos humanos",
      "Restaurantes",
      "Sistemas empresariales",
    ],
    proyectosDestacados: [
      "Microservicios con patrón BFF",
      "Aplicaciones móviles con React Native",
      "Soluciones de IA para procesos empresariales",
    ],
    perfilDestacado: true,
    orden: 6,
  },
];

export const filterCategories = [
  { id: "todos" as const, label: "Todos" },
  { id: "arquitectura" as const, label: "Arquitectura" },
  { id: "liderazgo" as const, label: "Liderazgo técnico" },
  { id: "backend" as const, label: "Backend" },
  { id: "frontend" as const, label: "Frontend" },
  { id: "fullstack" as const, label: "Full Stack" },
  { id: "cloud-devops" as const, label: "Cloud y DevOps" },
  { id: "bases-datos" as const, label: "Bases de datos" },
  { id: "integraciones" as const, label: "Integraciones y ERP" },
  { id: "qa" as const, label: "QA y automatización" },
];

const filterMap: Record<string, string[]> = {
  arquitectura: ["Arquitectura de software", "Arquitectura"],
  liderazgo: ["Liderazgo técnico"],
  backend: ["Backend"],
  frontend: ["Frontend"],
  fullstack: ["Full Stack"],
  "cloud-devops": ["Cloud y DevOps", "Cloud", "DevOps"],
  "bases-datos": ["Bases de datos"],
  integraciones: ["Integraciones", "Integraciones y ERP"],
  qa: ["QA y automatización"],
};

export function filterProfessionals(
  professionals: Professional[],
  category: string
): Professional[] {
  if (category === "todos") return professionals;
  const keywords = filterMap[category] || [];
  return professionals.filter((p) =>
    p.especialidades.some((e) =>
      keywords.some((kw) => e.toLowerCase().includes(kw.toLowerCase()))
    )
  );
}
