import type { Technology } from "@/types";

export const technologies: Technology[] = [
  { name: "TypeScript", icon: "TypeScript", category: "backend" },
  { name: "Node.js", icon: "NodeJs", category: "backend" },
  { name: "Python", icon: "Python", category: "backend" },
  { name: "Java", icon: "Java", category: "backend" },
  { name: "PHP", icon: "Php", category: "backend" },
  { name: ".NET", icon: "DotNet", category: "backend" },
  { name: "Next.js", icon: "NextJs", category: "frontend" },
  { name: "React", icon: "React", category: "frontend" },
  { name: "Vue.js", icon: "Vue", category: "frontend" },
  { name: "Angular", icon: "Angular", category: "frontend" },
  { name: "Tailwind CSS", icon: "Tailwind", category: "frontend" },
  { name: "HTML/CSS", icon: "Html", category: "frontend" },
  { name: "AWS", icon: "Aws", category: "cloud" },
  { name: "Azure", icon: "Azure", category: "cloud" },
  { name: "Google Cloud", icon: "GoogleCloud", category: "cloud" },
  { name: "DigitalOcean", icon: "DigitalOcean", category: "cloud" },
  { name: "PostgreSQL", icon: "Postgresql", category: "database" },
  { name: "MySQL", icon: "Mysql", category: "database" },
  { name: "MongoDB", icon: "MongoDb", category: "database" },
  { name: "Redis", icon: "Redis", category: "database" },
  { name: "SQL Server", icon: "SqlServer", category: "database" },
  { name: "Docker", icon: "Docker", category: "devops" },
  { name: "Kubernetes", icon: "Kubernetes", category: "devops" },
  { name: "Jenkins", icon: "Jenkins", category: "devops" },
  { name: "GitHub Actions", icon: "Github", category: "devops" },
  { name: "Terraform", icon: "Terraform", category: "devops" },
  { name: "OWASP", icon: "Shield", category: "security" },
  { name: "SonarQube", icon: "Search", category: "security" },
  { name: "Burp Suite", icon: "Bug", category: "security" },
  { name: "TensorFlow", icon: "Brain", category: "ai" },
  { name: "OpenAI", icon: "Sparkles", category: "ai" },
  { name: "Pandas", icon: "Table", category: "ai" },
];

export const technologyCategories = [
  { id: "backend" as const, label: "Backend" },
  { id: "frontend" as const, label: "Frontend" },
  { id: "cloud" as const, label: "Cloud" },
  { id: "database" as const, label: "Bases de datos" },
  { id: "devops" as const, label: "DevOps" },
  { id: "security" as const, label: "Seguridad" },
  { id: "ai" as const, label: "Inteligencia artificial" },
];
