import type { Technology } from "@/types";

export const technologies: Technology[] = [
  { name: "Node.js", icon: "NodeJs", category: "backend" },
  { name: "NestJS", icon: "NestJs", category: "backend" },
  { name: ".NET", icon: "DotNet", category: "backend" },
  { name: "C#", icon: "CSharp", category: "backend" },
  { name: "Java", icon: "Java", category: "backend" },
  { name: "Spring Boot", icon: "SpringBoot", category: "backend" },
  { name: "Golang", icon: "Golang", category: "backend" },
  { name: "Python", icon: "Python", category: "backend" },
  { name: "Django", icon: "Django", category: "backend" },
  { name: "PHP", icon: "Php", category: "backend" },
  { name: "Angular", icon: "Angular", category: "frontend" },
  { name: "React", icon: "React", category: "frontend" },
  { name: "Next.js", icon: "NextJs", category: "frontend" },
  { name: "React Native", icon: "React", category: "frontend" },
  { name: "Vue.js", icon: "Vue", category: "frontend" },
  { name: "TypeScript", icon: "TypeScript", category: "frontend" },
  { name: "JavaScript", icon: "JavaScript", category: "frontend" },
  { name: "Tailwind CSS", icon: "Tailwind", category: "frontend" },
  { name: "PostgreSQL", icon: "Postgresql", category: "database" },
  { name: "SQL Server", icon: "SqlServer", category: "database" },
  { name: "Oracle", icon: "Oracle", category: "database" },
  { name: "MySQL", icon: "Mysql", category: "database" },
  { name: "MongoDB", icon: "MongoDb", category: "database" },
  { name: "SAP HANA", icon: "SapHana", category: "database" },
  { name: "Redis", icon: "Redis", category: "database" },
  { name: "AWS", icon: "Aws", category: "cloud" },
  { name: "Azure", icon: "Azure", category: "cloud" },
  { name: "Docker", icon: "Docker", category: "devops" },
  { name: "GitHub Actions", icon: "Github", category: "devops" },
  { name: "AWS CodePipeline", icon: "Aws", category: "devops" },
  { name: "IIS", icon: "Iis", category: "devops" },
  { name: "Nginx", icon: "Nginx", category: "devops" },
  { name: "Linux", icon: "Linux", category: "devops" },
  { name: "GitLab", icon: "Gitlab", category: "devops" },
  { name: "SAP Business One", icon: "Sap", category: "integration" },
  { name: "SAP Service Layer", icon: "Sap", category: "integration" },
  { name: "Kafka", icon: "Kafka", category: "integration" },
  { name: "Node-RED", icon: "NodeRed", category: "integration" },
  { name: "APIs REST", icon: "Rest", category: "integration" },
  { name: "SFTP", icon: "Sftp", category: "integration" },
  { name: "WebSockets", icon: "WebSockets", category: "integration" },
  { name: "OpenAI", icon: "OpenAI", category: "ai" },
  { name: "Claude", icon: "Claude", category: "ai" },
  { name: "RAG", icon: "Rag", category: "ai" },
  { name: "MCP", icon: "Mcp", category: "ai" },
  { name: "n8n", icon: "N8n", category: "ai" },
  { name: "GitHub Copilot", icon: "Github", category: "ai" },
  { name: "Microsoft Copilot", icon: "Copilot", category: "ai" },
  { name: "Cursor", icon: "Cursor", category: "ai" },
];

export const technologyCategories = [
  { id: "backend" as const, label: "Backend" },
  { id: "frontend" as const, label: "Frontend" },
  { id: "database" as const, label: "Bases de datos" },
  { id: "cloud" as const, label: "Cloud" },
  { id: "devops" as const, label: "DevOps" },
  { id: "integration" as const, label: "Integraciones" },
  { id: "ai" as const, label: "Inteligencia artificial" },
];
